apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-um-deployment
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  selector:
    matchLabels:
      app: app-um-deployment
  template:
    metadata:
      labels:
        app: app-um-deployment
    spec:
      containers:
      - name: app-um-container
        image: registry.digitalocean.com/app-um/app-um-image
        imagePullPolicy: Always
        ports:
          - containerPort: 3333
            protocol: TCP
        readinessProbe:
          periodSeconds: 15
          timeoutSeconds: 2
          successThreshold: 2
          failureThreshold: 2
          httpGet:
            path: /
            port: 3333
        livenessProbe:
          exec:
            command:
            - yarn
            - migrate
          initialDelaySeconds: 5
          periodSeconds: 10
        env:
        - name: HELLO_ENV
          valueFrom:
            configMapKeyRef:
              name: app-env-config
              key: HELLO_ENV
        - name: DB_CONNECTION
          valueFrom:
            configMapKeyRef:
              name: app-env-config
              key: DB_CONNECTION
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: app-env-config
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: app-env-config
              key: DB_PORT
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: app-env-config
              key: DB_USER
        - name: DB_PASS
          valueFrom:
            configMapKeyRef:
              name: app-env-config
              key: DB_PASS
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: app-env-config
              key: DB_NAME
        - name: TIME_ZONE
          valueFrom:
            configMapKeyRef:
              name: app-env-config
              key: TIME_ZONE

      imagePullSecrets:
      - name: registry-app-um


